
FROM node:12-alpine as build-step
RUN mkdir -p /app
WORKDIR /app
COPY package*.json /app/
RUN npm install
RUN npm install -g @angular/cli
COPY . /app
EXPOSE 4200/tcp
RUN npm run build

FROM nginx:1.17.1-alpine
COPY --from=build-step app/dist/client /usr/share/nginx/html 