version: "3"
services:
  playground-web-frontend:
    image: playground-web-frontend:latest
    environment:
      PROXY_API: http://playground-web-backend:8080/
    ports:
      - 4200:4200
  playground-web-backend:
    image: playground-web-backend:latest
    env_file: .env
    restart: unless-stopped
    environment:
      MONGODB_LOCAL: ${MONGODB_LOCAL}
      DB_NAME: ${DB_NAME}
    depends_on:
      - mongo
    ports:
      - 8080:8080
  mongo:
    container_name: composemongo
    image: mongo:latest
    ports:
      - 27888:27017
